version: 2

workflows:
    version: 2
    package:
        jobs:
            - lint
            - test
            - release:
                  context: Master
                  requires:
                      - lint
                      - test

commands:
    prepare_workspace:
        steps:
            - restore_cache:
                  name: Restore npm package cache
                  keys:
                      - npm-packages-{{ checksum "package-lock.json" }}
            - run:
                  name: Install Dependencies
                  command: |
                      npm i
            - save_cache:
                  name: Save npm package cache
                  key: npm-packages-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules

executors:
    node:
        docker:
            - image: 'cimg/node:17.9.1'

jobs:
    lint:
        resource_class: small
        executor: node
        steps:
            - checkout
            - prepare_workspace
            - run:
                  name: Lint
                  command: npm run lint
    test:
        resource_class: small
        executor: node
        parallelism: 8
        steps:
            - checkout
            - prepare_workspace
            - run:
                  name: Test
                  command: npx jest --maxWorkers=8
    release:
        resource_class: small
        executor: node
        steps:
            - checkout
            - run:
                  name: Copy src/package.json to dist for verification release
                  command: |
                      mkdir -p ./dist
                      cp src/package.json dist/package.json
            - run:
                  name: Semantic Release
                  command: npx semantic-release
