version: 2

workflows:
    version: 2
    package:
        jobs:
            - release:
                  context: Master

jobs:
    test:
        docker:
            - image: 'cimg/node:18.11.0'
        steps:
            - checkout
    release:
        docker:
            - image: 'cimg/node:18.11.0'
        parallelism: 4
        steps:
            - checkout
            - restore_cache:
                  name: Restore npm Package Cache
                  keys:
                      - npm-packages-{{ checksum "package-lock.json" }}
            - run:
                  name: Install Dependencies
                  command: |
                      npm install
                      npm install semantic-release@19 @semantic-release/exec@6 -D
            - save_cache:
                  name: Save npm Package Cache
                  key: npm-packages-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules
            - run:
                  name: lint
                  command: npm run lint
            - run:
                  name: test
                  command: npm run test --maxWorkers=4
            - run:
                  name: Copy package.json to ./dist for verification release
                  command: |
                      mkdir -p ./dist
                      cp ./src/package.json ./dist/package.json
            - run:
                  name: semantic release
                  command: npx semantic-release
