version: 2

workflows:
    version: 2
    package:
        jobs:
            - release:
                  context: Master

jobs:
    test:
        docker:
            - image: 'cimg/node:17.1.0'
        steps:
            - checkout
    release:
        docker:
            - image: 'cimg/node:17.1.0'
        parallelism: 10
        steps:
            - checkout
            - restore_cache:
                  name: Restore pnpm Package Cache
                  keys:
                      - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Install Dependencies
                  command: |
                      npx pnpm install
            - save_cache:
                  name: Save pnpm Package Cache
                  key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - node_modules
            - run:
                  name: lint
                  command: npx pnpm run lint
            - run:
                  name: test
                  command: npx jest --maxWorkers=4
            - run:
                  name: Copy package.json to ./dist for verification release
                  command: mkdir -p ./dist && cp ./src/package.json ./dist/package.json
            - run:
                  name: semantic release
                  command: npx semantic-release || true
