version: 2.1

workflows:
    package:
        jobs:
            - setup
            - lint:
                  requires:
                      - setup
            - test:
                  requires:
                      - setup
            - release:
                  context: Master
                  requires:
                      - lint
                      - test

aliases:
    - &working_directory ~/repo

commands:
    prepare_workspace:
        steps:
            - attach_workspace:
                  at: *working_directory

executors:
    node17:
        docker:
            - image: 'cimg/node:17.9.1'
        resource_class: small
        working_directory: *working_directory

jobs:
    setup:
        executor: node17
        steps:
            - prepare_workspace
            - checkout
            - restore_cache:
                  name: Restore npm package cache
                  keys:
                      - npm-packages-{{ checksum "package-lock.json" }}
            - run:
                  name: Install Dependencies
                  command: |
                      npm i
            - save_cache:
                  name: Save npm package cache
                  key: npm-packages-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules
    lint:
        executor: node17
        steps:
            - prepare_workspace
            - checkout
            - run:
                  name: Lint
                  command: npm run lint
    test:
        executor: node17
        parallelism: 4
        steps:
            - prepare_workspace
            - checkout
            - run:
                  name: Test
                  command: npx jest --maxWorkers=4
    release:
        executor: node17
        steps:
            - prepare_workspace
            - checkout
            - run:
                  name: Copy src/package.json to dist for verification release
                  command: |
                      mkdir -p ./dist
                      cp src/package.json dist/package.json
            - run:
                  name: Semantic Release
                  command: npx semantic-release
