name: Check title of pull request
on:
    pull_request_target:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    lint:
        timeout-minutes: 15
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [18.12.1]
        steps:
            - uses: aslafy-z/conventional-pr-title-action@main
              with:
                  success-state: follows the aron-conventional-commits
                  failure-state: doesn't follow the aron-conventional-commits
                  context-name: Title of pull request
                  preset: conventional-changelog-aron
                  target-url: https://github.com/1aron/aronrepo/tree/beta/packages/conventional-commits
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
