name: Commit Check
on:
    push:
        branches:
            - "**"
    pull_request_target:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    check:
        name: "commit-check"
        timeout-minutes: 20
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [18]
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm run build
            - run: pnpm run commit-check
