name: Check title of pull request
on:
    pull_request_target:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    check:
        timeout-minutes: 25
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [18.17.0]
        steps:
            - name: Aron Actions
              uses: 1aron/techor@v2.5.2
              with:
                  action: "check-pull-request-title"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
