name: Sync dev branches
on:
    push:
        branches:
            - "*"

jobs:
    sync:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Techor Actions
              uses: 1aron/techor@v2.5.17
              with:
                  action: "sync-dev-branches"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
