name: Sync dev branches
on:
    push:
        branches:
            - "*"

jobs:
    check:
        timeout-minutes: 15
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Techor Actions
              uses: 1aron/techor@v2.5.5
              with:
                  action: "sync-dev-branches"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
